### ISSUE TITLE
Max Channel is 575

### ISSUE THREAD

**Issue by tdubbs** [ToddGreenfield/homebridge-directv#12]
It looks like the highest channel per the slider in new scene is 575. Directv has channels up to 9999. 

I'd guess the sensitivity of the slider needed to be cut off which is why its at 575. Is there a work around for this?

**Comment by apexad** [comment]
Channel could be changed to a string, but when I tested it in Eve, it did not handle it as well as I would have hoped. Could just change it to 9999 as integer too.

I certainly hope nobody is actually using the slider to select a channel, that would be crazy!

**Comment by ToddGreenfield** [comment]
We could certainly make config options for low/high thresholds for the channel slider, but I dont know of another way to allow for this. The problem is actually using the slider to set the channel. I dont think anyone would use the slider itself for anything other than setting up a scene. This idea is not efficient, but perhaps you could use a low/high config value, say 0-500, then create scenes for those channels. Then reset/restart with 500-1000 (or whatever) and create those scenes. Then when all scenes are set, redo the config for 1-9999 or whatever. The scenes should work then. Honestly, I don't really use this plug anymore as I use HarmonyHubs for all my AV, including DTVs. Feel free to do a PR- @apexad I gave privs to collaborate a while back...

**Comment by tdubbs** [comment]
What's the optimal procedure for setting a scene to channel say 628? (NESN Redsox) My goal is to say "Siri, turn channel to redsox" , Redsox being the scene name.

**Comment by ToddGreenfield** [comment]
When I originally setup my channel scenes I used the slider with a stylus to select, but it took a few attempts to get the correct channel number. Right now the channel only goes to 575 so setting to anything higher isn't an option without modifying the plugin.

**Comment by ToddGreenfield** [comment]
@tdubbs I updated the plugin this morning. Upgrade to the latest version and be sure to update the config settings.
To allow for ease of setting up channel scenes: 1) Temporarily set reasonable values for min/max channel config settings; 2) Restart homebridge, setup channel scenes in that range; 3) Repeat steps 1-2 as needed; 4) Finally update config with min value of 1 and max of 9999, then restart homebridge. All scenes should work fine.
Let me know if this works for you.

**Comment by apexad** [comment]
I was able to just tune the TV to the channel I want to setup a scene for and Eve defaults to that channel when setting up a scene. Anyway, looks like you already did the Min/Max thing.

I've been very busy, but will do some work on this plugin again when I can. In regards to favorite channels, setting them up as switches might be a possibility, rather than scenes.
