### ISSUE TITLE
Exposing other buttons

### ISSUE THREAD

**Issue by apexad** [ToddGreenfield/homebridge-directv#3]
It would be interesting to expose othe buttons, like Guide, List, Channel Up, Channel Down, and the Arrow keys. These switches would need to turn on, do the action, then shut off again in about 500 milliseconds in my testing.
It would allow a room to be created that could look something like this:
![img_0991](https://cloud.githubusercontent.com/assets/1437332/25301288/a51c2a5a-26d7-11e7-9b62-a3ca7bccdc5c.PNG)

**Comment by ToddGreenfield** [comment]
I am thinking this might be best done dynamically using the v2.0 api of homebridge. The buttons all leverage the same directv-remote function processKey, so rather than program all of the buttons you want, you could just do one function and let the user dynamically add whatever remote functions. The pllugin would need to be modified to use the v2 api though...  I have been looking at it recently as I work on another plugin (homebridge-nut)...

**Comment by apexad** [comment]
Is homebridge API v2.0 compatible with the Home App?  Or only Eve? Or even maybe just Hesperus (or however you spell that)?

**Comment by mreassassin** [comment]
I would love this!

**Comment by ToddGreenfield** [comment]
Feel free to do a PR.
